export enum PhoneNumberStatus {
  STATUS_OK = "STATUS_OK",
  STATUS_WAIT_CODE = "STATUS_WAIT_CODE",
  STATUS_CANCEL = "STATUS_CANCEL",
  STATUS_WAIT_RESEND = "STATUS_WAIT_RESEND",
  STATUS_ACCESS = "STATUS_ACCESS",
  STATUS_WAIT_STATUS = "STATUS_WAIT_STATUS",
  STATUS_UNKNOWN = "STATUS_UNKNOWN",
}